function s = register_component_library(path, link_register, ask_dialog)
    
    if ~exist('link_register', 'var')
        link_register = 0;
    end
    
    if ~exist('ask_dialog', 'var')
        ask_dialog = 1;
    end

    s = 0;
    if isfolder(path)

        if endsWith(path, '/')
            path = path(1:end-1);
        end
        meta = readstruct(fullfile(path, 'package.json'));
        reg = CSPath.get_app_registry_path();
        name = meta.Name;
    
        msg = "Library already exists. Do you want to override existing library?";
        title = "Library exists";
        if exist(fullfile(reg, name), 'dir') ...
            
            if ask_dialog
                answer = questdlg(msg, title, {"Yes", "No"});
            else
                answer = "Yes";
            end
            if ~strcmp(answer, "Yes")
                return
            end
            rmdir(fullfile(reg, name), 's');
        elseif exist(fullfile(reg, strcat(name, '.json')), 'file')
            if ask_dialog
                answer = questdlg(msg, title, {"Yes", "No"});
            else
                answer = "Yes";
            end
            if ~strcmp(answer, "Yes")
                return
            end
            delete(fullfile(reg, strcat(name, '.json')));
        end

        if ~link_register
            dest_path = fullfile(reg, name);
            paths = library_paths(path, name);
            addpath(paths{:});
            copyfile(path, dest_path);
        else
            link_lib.Path = path;
            link_lib.Version = meta.Version;
            writestruct(link_lib, fullfile(reg, strcat(name, '.json')));
            dest_path = path;
        end
        % remove autogen folder, because it will be autogenerated
        if isfolder(fullfile(dest_path, 'autogen'))
            rmpath(fullfile(dest_path, 'autogen'));
            rmdir(fullfile(dest_path, 'autogen'), "s");
        end

        handle = get_or_create_component_library(dest_path);
        plugin_desc_path = fullfile(dest_path, 'plugins.json');
        registry = make_component_registry_from_plugin_description(plugin_desc_path, ...
            name, fullfile(dest_path, 'autogen'));

        fnames = fieldnames(registry);
        types = get_component_types();
        for i=1:length(fnames)
            fname = fnames{i};
            if ~any(arrayfun(@(x) strcmp(fname, x), types))
                warning(strcat("Found unknown component type '", fname, "'."));
                continue
            end

            plugin_list = registry.(fname);
            for j = 1:length(plugin_list)
                register_component(plugin_list{j}, parse_comp_type(fname), handle.name, handle.path, 0);
            end
        end

        % remove old library from path
        if ~link_register
            rmpath(paths{:});
        end

        new_paths = get_library_folder_paths(dest_path, name);
        addpath(new_paths{:});
        close_library(name);
        s = 1;
    else
        error("Provided path is not a folder");
    end
end


